//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleAdornos.Repositorio.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tipo_Material_Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tipo_Material_Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleAdornos.Repositorio.Queries.Tipo_Material_Queries", typeof(Tipo_Material_Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE tipo_material 
        ///SET descricao = @descricao 
        ///WHERE id = @id.
        /// </summary>
        internal static string AlterarTipo_Material {
            get {
                return ResourceManager.GetString("AlterarTipo_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM tipo_material 
        ///WHERE id = @id.
        /// </summary>
        internal static string ApagarTipo_Material {
            get {
                return ResourceManager.GetString("ApagarTipo_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS tipo_material
        ///(id INTEGER PRIMARY KEY, 
        ///descricao VARCHAR(30)).
        /// </summary>
        internal static string CriarTabelaTipo_Material {
            get {
                return ResourceManager.GetString("CriarTabelaTipo_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tipo_material(descricao) 
        ///VALUES(@descricao).
        /// </summary>
        internal static string InserirTipo_Material {
            get {
                return ResourceManager.GetString("InserirTipo_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, descricao 
        ///FROM tipo_material.
        /// </summary>
        internal static string ObterTipo_Materiais {
            get {
                return ResourceManager.GetString("ObterTipo_Materiais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, descricao 
        ///FROM tipo_material 
        ///WHERE id = @id.
        /// </summary>
        internal static string ObterTipo_MaterialPorId {
            get {
                return ResourceManager.GetString("ObterTipo_MaterialPorId", resourceCulture);
            }
        }
    }
}
