//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeLetras {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleDeLetras.Resource-Queries", typeof(Resource_Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS material(id INTEGER PRIMARY KEY, descricao VARCHAR(30), tipo_material_id INTEGER, quantidade INTEGER, FOREIGN KEY(tipo_material_id) REFERENCES tipo_material(id)).
        /// </summary>
        internal static string MATERIAL_CREATE_TABLE {
            get {
                return ResourceManager.GetString("MATERIAL_CREATE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM material WHERE id = @id.
        /// </summary>
        internal static string MATERIAL_DELETE {
            get {
                return ResourceManager.GetString("MATERIAL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO material(descricao, tipo_material_id, quantidade) VALUES(@descricao, @tipo_material_id, @quantidade).
        /// </summary>
        internal static string MATERIAL_INSERT {
            get {
                return ResourceManager.GetString("MATERIAL_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, descricao, tipo_material_id, quantidade FROM material.
        /// </summary>
        internal static string MATERIAL_SELECT {
            get {
                return ResourceManager.GetString("MATERIAL_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT material.id, material.descricao, material.tipo_material_id, tipo_material.descricao, material.quantidade FROM material INNER JOIN tipo_material ON tipo_material.id = material.tipo_material_id.
        /// </summary>
        internal static string MATERIAL_SELECT_JOIN_TIPO_MATERIAL {
            get {
                return ResourceManager.GetString("MATERIAL_SELECT_JOIN_TIPO_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, descricao, tipo_material_id, quantidade FROM material WHERE id = @id.
        /// </summary>
        internal static string MATERIAL_SELECT_POR_ID {
            get {
                return ResourceManager.GetString("MATERIAL_SELECT_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE material SET descricao = @descricao, tipo_material_id = @tipo_material_id, quantidade = @quantidade WHERE id = @id.
        /// </summary>
        internal static string MATERIAL_UPDATE {
            get {
                return ResourceManager.GetString("MATERIAL_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE material SET quantidade = quantidade + @quantidade WHERE id = @id.
        /// </summary>
        internal static string MATERIAL_UPDATE_QUANTIDADE {
            get {
                return ResourceManager.GetString("MATERIAL_UPDATE_QUANTIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS palavras(id INTEGER PRIMARY KEY, descricao VARCHAR(15)).
        /// </summary>
        internal static string PALAVRAS_CREATE_TABLE {
            get {
                return ResourceManager.GetString("PALAVRAS_CREATE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM palavras WHERE id = @id.
        /// </summary>
        internal static string PALAVRAS_DELETE {
            get {
                return ResourceManager.GetString("PALAVRAS_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO palavras (descricao) VALUES(@descricao).
        /// </summary>
        internal static string PALAVRAS_INSERT {
            get {
                return ResourceManager.GetString("PALAVRAS_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, descricao FROM palavras.
        /// </summary>
        internal static string PALAVRAS_SELECT {
            get {
                return ResourceManager.GetString("PALAVRAS_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE palavras SET descricao = @descricao WHERE id = @id.
        /// </summary>
        internal static string PALAVRAS_UPDATE {
            get {
                return ResourceManager.GetString("PALAVRAS_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS tipo_material(id INTEGER PRIMARY KEY, descricao VARCHAR(30)).
        /// </summary>
        internal static string TIPO_MATERIAL_CREATE_TABLE {
            get {
                return ResourceManager.GetString("TIPO_MATERIAL_CREATE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM tipo_material WHERE id = @id.
        /// </summary>
        internal static string TIPO_MATERIAL_DELETE {
            get {
                return ResourceManager.GetString("TIPO_MATERIAL_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO tipo_material(descricao) VALUES(@descricao).
        /// </summary>
        internal static string TIPO_MATERIAL_INSERT {
            get {
                return ResourceManager.GetString("TIPO_MATERIAL_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, descricao FROM tipo_material.
        /// </summary>
        internal static string TIPO_MATERIAL_SELECT {
            get {
                return ResourceManager.GetString("TIPO_MATERIAL_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id, descricao FROM tipo_material WHERE id = @id.
        /// </summary>
        internal static string TIPO_MATERIAL_SELECT_POR_ID {
            get {
                return ResourceManager.GetString("TIPO_MATERIAL_SELECT_POR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE tipo_material SET descricao = @descricao WHERE id = @id.
        /// </summary>
        internal static string TIPO_MATERIAL_UPDATE {
            get {
                return ResourceManager.GetString("TIPO_MATERIAL_UPDATE", resourceCulture);
            }
        }
    }
}
