//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleAdornos.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMensagensPadrao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensPadrao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleAdornos.Util.ResourceMensagensPadrao", typeof(ResourceMensagensPadrao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação cancelada..
        /// </summary>
        internal static string CANCELADO {
            get {
                return ResourceManager.GetString("CANCELADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma alteração?.
        /// </summary>
        internal static string CONFIRMA_ALTERACAO {
            get {
                return ResourceManager.GetString("CONFIRMA_ALTERACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma inclusão?.
        /// </summary>
        internal static string CONFIRMA_INCLUSAO {
            get {
                return ResourceManager.GetString("CONFIRMA_INCLUSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma remoção?.
        /// </summary>
        internal static string CONFIRMA_REMOCAO {
            get {
                return ResourceManager.GetString("CONFIRMA_REMOCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvo com sucesso!.
        /// </summary>
        internal static string SALVO {
            get {
                return ResourceManager.GetString("SALVO", resourceCulture);
            }
        }
    }
}
